#!/bin/sh
for param in $(cat /proc/cmdline) ; do
    case "${param}" in
        root=*)
            root="${param#root=}"
            ;;
    esac
done

mount -a -T /etc/fstab

mount $root /mnt/root

modprobe zram num_devices=1
echo $(du /mnt/root/rootfs.sqfs -b | cut -f1 | echo $(($(cat)+1000000))) > /sys/block/zram0/disksize
mount /dev/zram0 /mnt/zram


mount -t overlay -o lowerdir=/mnt/zram, upperdir=/mnt/root/overlay, workdir=/mnt/root/workdir overlay /mnt/newroot

switch_root /mnt/newroot
