#!/bin/sh
mount -a -T /etc/fstab

for param in $(cat /proc/cmdline) ; do
    case "${param}" in
        root=*)
            root="${param#root=}"
            ;;
    esac
done


mkdir /lib/modules/$(uname -r)/kernel -p
cp /tmpmod/* /lib/modules/$(uname -r)/kernel/ -r

mount $root /mnt/root

modprobe zram num_devices=$((1+$(ls /mnt/root/addons | wc -l)))
echo $(du /mnt/root/rootfs.sqfs -b | cut -f1 | echo $(($(cat)+1000000))) > /sys/block/zram0/disksize
dd if=/mnt/root/rootfs.sqfs of=/dev/zram0
mount /dev/zram0 /mnt/zram

mkdir /mnt/root/addons -p
cd /mnt/root/addons/
i=1
for f in *; do if [ -f $f ]
then
	mkdir /mnt/addons/$(echo $f | sed 's/.sqfs//g') -p
	echo $(du /mnt/root/addons/$f -b | cut -f1 | echo $(($(cat)+1000000))) > /sys/block/zram$i/disksize
	dd if=/mnt/root/addons/$f of=/dev/zram$i
	mount /dev/zram$i /mnt/addons/$(echo $f | sed 's/.sqfs//g')
	i=$(($i+1))
fi
done
cd /

addons=$(ls /mnt/addons/ | xargs echo | echo "/mnt/addons/$(cat )" | sed 's/ /:\/mnt\/addons\//g')
[ "x$addons" != "x" ] && addons=":$addons"

mount -t overlay -o lowerdir="/mnt/zram$addons",upperdir=/mnt/root/overlay,workdir=/mnt/root/workdir overlay /mnt/newroot

exec switch_root /mnt/newroot /init
